spring:
  profiles:
    active:
      - dev
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    format_sql: true
#    generate-ddl: true
    hibernate:
      ddl-auto: update

  mail:
#    host: smtp.naver.com #smtp 네이버 서버 주소
#    port: 465 # 메일 인증서버 포트 :smtp
    host: smtp.gmail.com #smtp 구글 서버 주소
    port: 587 # 메일 인증서버 포트 :smtps
    protocol: smtps
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            enable: true #반드시 필요 -> SSL 필요로 되어있으면

#  task:
#    scheduling:
#      pool:
#        size: 50
#      thread-name-prefix: test

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800 # 세션 유지 시간 (60 = 1분)