spring:
  profiles:
    active:
      - dev
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    format_sql: true
    hibernate:
      ddl-auto: update

#    generate-ddl: true
#  task:
#    scheduling:
#      pool:
#        size: 50
#      thread-name-prefix: test
  mail:
    host: smtp.naver.com #smtp 서버 주소
    port: 465 # 메일 인증서버 포트
    properties:
      mail:
        smtp:
          starttls:
            enable: true
#            required: true
          auth: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
          ssl:
#trust: smtp.naver.com
            enable: true #반드시 필요 -> SSL 필요로 되어있으면

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
server:
  port: 8080
